from __future__ import annotations

from .models import ContractOperation, PublicApiContract

_OPERATIONS = (
    ContractOperation(
        id="list-apps",
        method="get",
        runtime_path="/v1/apps",
        sdk_name="listApps",
        summary="List apps",
        description="Return developer apps available to the current principal.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="create-app",
        method="post",
        runtime_path="/v1/apps",
        sdk_name="createApp",
        summary="Create app",
        description="Create a developer app and reveal its client secret once.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="create-app-token",
        method="post",
        runtime_path="/v1/apps/token",
        sdk_name="createAppToken",
        summary="Create app token",
        description="Exchange app client credentials for a developer bearer token.",
        auth_kind="public",
        docs_group="apps",
    ),
    ContractOperation(
        id="get-app",
        method="get",
        runtime_path="/v1/apps/{app_id}",
        sdk_name="getApp",
        summary="Get app",
        description="Fetch one developer app.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="create-installation",
        method="post",
        runtime_path="/v1/apps/{app_id}/installations",
        sdk_name="createInstallation",
        summary="Create installation",
        description="Install a developer app into a project or server scope.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="list-installations",
        method="get",
        runtime_path="/v1/installations",
        sdk_name="listInstallations",
        summary="List installations",
        description="Return installations visible to the current principal.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="create-installation-token",
        method="post",
        runtime_path="/v1/installations/{installation_id}/tokens",
        sdk_name="createInstallationToken",
        summary="Create installation token",
        description="Issue a scoped bearer token for an existing installation.",
        auth_kind="mixed",
        docs_group="apps",
    ),
    ContractOperation(
        id="get-me",
        method="get",
        runtime_path="/v1/me",
        sdk_name="getMe",
        summary="Get current developer principal",
        description="Return the current developer user profile when authenticated.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="list-my-projects",
        method="get",
        runtime_path="/v1/me/projects",
        sdk_name="listMyProjects",
        summary="List my projects",
        description="Return owned or managed projects for the current user.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="list-my-servers",
        method="get",
        runtime_path="/v1/me/servers",
        sdk_name="listMyServers",
        summary="List my servers",
        description="Return owned or managed servers for the current user.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="get-openapi",
        method="get",
        runtime_path="/v1/openapi.json",
        sdk_name=None,
        summary="Get public OpenAPI document",
        description="Return the generated public developer OpenAPI schema.",
        auth_kind="public",
        docs_group="overview",
        include_in_sdk=False,
    ),
    ContractOperation(
        id="list-pat-tokens",
        method="get",
        runtime_path="/v1/pat-tokens",
        sdk_name="listPersonalAccessTokens",
        summary="List personal access tokens",
        description="Return developer PATs owned by the current user.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="create-pat-token",
        method="post",
        runtime_path="/v1/pat-tokens",
        sdk_name="createPersonalAccessToken",
        summary="Create personal access token",
        description="Issue a developer PAT through the public facade.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="revoke-pat-token",
        method="delete",
        runtime_path="/v1/pat-tokens/{token_id}",
        sdk_name="revokePersonalAccessToken",
        summary="Revoke personal access token",
        description="Revoke a PAT owned by the current user.",
        auth_kind="bearer",
        docs_group="auth",
    ),
    ContractOperation(
        id="list-projects",
        method="get",
        runtime_path="/v1/projects",
        sdk_name="listProjects",
        summary="List projects",
        description="List public projects through the stable developer facade.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="get-project-filter-stats",
        method="get",
        runtime_path="/v1/projects/stats",
        sdk_name="getProjectFilterStats",
        summary="Get project filter stats",
        description="Return aggregated project counts for the active developer filters.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="resolve-project",
        method="get",
        runtime_path="/v1/projects/resolve/{project_ref}",
        sdk_name="resolveProject",
        summary="Resolve project",
        description="Resolve a public project id, slug, or entrypoint.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="get-project",
        method="get",
        runtime_path="/v1/projects/{project_ref}",
        sdk_name="getProject",
        summary="Get project",
        description="Return one public project summary.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="list-project-servers",
        method="get",
        runtime_path="/v1/projects/{project_ref}/servers",
        sdk_name="listProjectServers",
        summary="List project servers",
        description="Return public servers attached to one project.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="get-project-team",
        method="get",
        runtime_path="/v1/projects/{project_ref}/team",
        sdk_name="getProjectTeam",
        summary="Get project team",
        description="Return the public team view for one project.",
        auth_kind="public",
        docs_group="projects",
    ),
    ContractOperation(
        id="list-servers",
        method="get",
        runtime_path="/v1/servers",
        sdk_name="listServers",
        summary="List servers",
        description="List public servers through the stable developer facade.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server-filter-stats",
        method="get",
        runtime_path="/v1/servers/stats",
        sdk_name="getServerFilterStats",
        summary="Get server filter stats",
        description="Return aggregated server counts for the active developer filters.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server",
        method="get",
        runtime_path="/v1/servers/{server_ref}",
        sdk_name="getServer",
        summary="Get server",
        description="Return one public server summary.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server-engagement",
        method="get",
        runtime_path="/v1/servers/{server_ref}/engagement",
        sdk_name="getServerEngagement",
        summary="Get server engagement",
        description="Return the public engagement summary for one server.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server-history",
        method="get",
        runtime_path="/v1/servers/{server_ref}/history",
        sdk_name="getServerHistory",
        summary="Get server history",
        description="Return historical player and uptime points for one server.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server-live",
        method="get",
        runtime_path="/v1/servers/{server_ref}/live",
        sdk_name="getServerLive",
        summary="Get server live status",
        description="Return the current live status snapshot for one server.",
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="get-server-launch-manifest",
        method="get",
        runtime_path="/v1/servers/{server_ref}/launch-manifest",
        sdk_name="getServerLaunchManifest",
        summary="Get server launch manifest",
        description=(
            "Return the LeavePulse launcher manifest for a server: Minecraft "
            "version, mod loader, mods/resourcepacks (inline or .mrpack), "
            "JVM hints, and connection address."
        ),
        auth_kind="public",
        docs_group="servers",
    ),
    ContractOperation(
        id="list-webhooks",
        method="get",
        runtime_path="/v1/webhooks",
        sdk_name="listWebhooks",
        summary="List webhooks",
        description="Return webhooks visible to the current principal.",
        auth_kind="mixed",
        docs_group="webhooks",
    ),
    ContractOperation(
        id="create-webhook",
        method="post",
        runtime_path="/v1/webhooks",
        sdk_name="createWebhook",
        summary="Create webhook",
        description="Create a developer webhook subscription.",
        auth_kind="mixed",
        docs_group="webhooks",
    ),
    ContractOperation(
        id="delete-webhook",
        method="delete",
        runtime_path="/v1/webhooks/{webhook_id}",
        sdk_name="deleteWebhook",
        summary="Delete webhook",
        description="Delete a webhook owned by the current principal.",
        auth_kind="mixed",
        docs_group="webhooks",
    ),
    ContractOperation(
        id="list-webhook-deliveries",
        method="get",
        runtime_path="/v1/webhooks/{webhook_id}/deliveries",
        sdk_name="listWebhookDeliveries",
        summary="List webhook deliveries",
        description="Return recent deliveries for a webhook.",
        auth_kind="mixed",
        docs_group="webhooks",
    ),
)

GROUP_METADATA = {
    "overview": (
        "Overview",
        "Start here for the public contract and SDK generation surface.",
    ),
    "auth": (
        "Authentication",
        "Developer identity, PAT lifecycle and current-user endpoints.",
    ),
    "apps": (
        "Apps",
        "Developer app registration, installations and installation tokens.",
    ),
    "projects": (
        "Projects",
        "Public project catalog, team visibility and project filter stats.",
    ),
    "servers": (
        "Servers",
        "Public server catalog, live snapshots, history and engagement views.",
    ),
    "webhooks": (
        "Webhooks",
        "Webhook subscription management and delivery inspection.",
    ),
}

PUBLIC_API_CONTRACT = PublicApiContract(
    title="LeavePulse Developer API",
    version="1.0.0",
    description="Stable public developer contract for LeavePulse.",
    runtime_prefix="/v1",
    canonical_base_url="https://api.leavepulse.com/v1",
    operations=_OPERATIONS,
)
